sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t rhys117/slack-time -f ./backend/Dockerfile.dev ./backend

scripts:
  - docker run -e CI=true rhys117/slack-time rspec

after_success:
  - docker build -t rhys117/slack-time ./backend
  # Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take image and push to docker hub
  - docker push rhys117/slack-time