version: '3'

services:
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./backend
    volumes:
      - ./backend:/usr/src/app
    ports:
      - '4567:4567'
    env_file:
      - backend/.env
