source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

ruby '2.5.5'

gem 'sinatra'
gem 'pry'

group :development do
  gem 'sinatra-reloader'
  gem 'dotenv'
end

group :test do
  gem 'rack-test'
  gem 'rspec'
end